### PR TITLE
Replace non-standard own-made assert methods by the standard ones

### PR DESCRIPTION
**Pull request by mcepl**
There is no need to replicate badly assert methods which are already in the standard library.

### CODE REVIEW

**Comment by kovidgoyal** [comment]
I would imagine that the original author of cssutils used these because at the time the equivalent functionality didnt exist in the stdlib.

**Comment by kovidgoyal** [comment]
And you will need to re-implement them for python 2 yourself since css-parser still supports py2, maybe you will do a better job than the original developer.

**Comment by mcepl** [comment]
> I would imagine that the original author of cssutils used these because at the time the equivalent functionality didnt exist in the stdlib.

Yes, but even if I imagine that you support 2.7 (and by the way, seriously, why?) then it is certainly not necessary to have a code to support 2.4 (which I found in places).

OK, I will add some 2.* code (seriously, why?).

**Comment by kovidgoyal** [comment]
On Tue, Jan 25, 2022 at 11:47:19PM -0800, Matěj Cepl wrote:
> > I would imagine that the original author of cssutils used these because at the time the equivalent functionality didnt exist in the stdlib.
> 
> Yes, but even if I imagine that you support 2.7 (and by the way, seriously, why?) then it is certainly not necessary to have a code to support 2.4 (which I found in places).
> 
> OK, I will add some 2.* code (seriously, why?).

because I dont drop support for things for no good reason (seriously,
why wouldanyone consider that a good idea?)

**Comment by mcepl** [comment]
> because I dont drop support for things for no good reason (seriously, why wouldanyone consider that a good idea?)

Because your programs will become unmaintainable mess? How is your support for Python 1.5 going?

**Comment by kovidgoyal** [comment]
On Wed, Jan 26, 2022 at 12:52:51AM -0800, Matěj Cepl wrote:
> > because I dont drop support for things for no good reason (seriously, why wouldanyone consider that a good idea?)
> 
> Because your programs will become unmaintainable mess? How is your support for Python 1.5 going?

I've been maintaining software for 25 years none of it has yet become an
unmaintainable mess, so I think I'll stick with the existing code, thanks.

**Comment by mcepl** [comment]
> I've been maintaining software for 25 years none of it has yet become an unmaintainable mess, so I think I'll stick with the existing code, thanks.

Why did you close it, please? I have provided your py2k compatibility fixes (not that I agree with the idea, but it is your project).

**Comment by kovidgoyal** [comment]
Because given your attitude I dont feel like spending my valuable time reviewing this

**Comment by mcepl** [comment]
Right, so you are a self-righteous jerk who cares more about how puffed up you are than about the matter. Thank you for ignoring those hours spending on wrangling with that mess you had to make it working better.

**Comment by kovidgoyal** [comment]
Arrah patsy mind the baby, arrah patsy mind th echild, he'll kick and bite and cry all night.

**Pull request closed without merging**
